// src/core/types/execution-graph.ts

import { AgentStageConfig } from '../../config/schema.js';

/**
 * Represents a node in the execution graph (DAG)
 */
export interface ExecutionNode {
  stage: AgentStageConfig;
  dependencies: string[];              // Stage names this node depends on
  dependents: string[];                // Stage names that depend on this node
  level: number;                       // Topological level (0 = no deps, 1 = depends on level 0, etc.)
}

/**
 * Execution group - stages that can run in parallel
 */
export interface ExecutionGroup {
  level: number;                       // Execution level (groups run sequentially, stages within run parallel)
  stages: AgentStageConfig[];          // Stages in this group
}

/**
 * Complete execution plan generated by DAG planner
 */
export interface ExecutionPlan {
  groups: ExecutionGroup[];            // Ordered list of execution groups
  totalStages: number;
  maxParallelism: number;              // Max number of stages running in parallel
  isSequential: boolean;               // True if no parallelism possible
}

/**
 * DAG validation result
 */
export interface DAGValidation {
  valid: boolean;
  errors: string[];                    // Critical errors (cycles, missing deps)
  warnings: string[];                  // Non-critical issues
}

/**
 * Execution graph - complete DAG representation
 */
export interface ExecutionGraph {
  nodes: Map<string, ExecutionNode>;   // Stage name -> node
  adjacencyList: Map<string, string[]>; // Stage name -> dependencies
  plan: ExecutionPlan;
  validation: DAGValidation;
}
