name: commit-review
trigger: post-commit

# Git workflow configuration (Phase 4)
git:
  baseBranch: main
  branchStrategy: reusable
  branchPrefix: pipeline
  pullRequest:
    autoCreate: true
    title: "🤖 Automated Code Review & Quality Improvements"
    reviewers: []
    labels:
      - automated
      - code-review
    draft: false

# Notification configuration (Phase 5)
notifications:
  enabled: true
  events:
    - pipeline.completed
    - pipeline.failed
    - pr.created
  channels:
    local:
      enabled: true
      sound: true
      openUrl: true
    # slack:
    #   enabled: false
    #   webhookUrl: ${SLACK_WEBHOOK_URL}  # Or set directly here
    #   mentionOnFailure:
    #     - channel

settings:
  autoCommit: true
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: continue
  preserveWorkingTree: false
  # permissionMode: acceptEdits  # default: auto-accept file edits (respects .claude/settings.json rules)

  # claudeAgent:                 # Optional: Claude Agent SDK settings
  #   model: sonnet              # haiku (fast/cheap) | sonnet (balanced) | opus (powerful)
  #   maxTurns: 15               # Max conversation turns
  #   maxThinkingTokens: 5000    # Extended thinking budget

agents:
  - name: code-review
    agent: .claude/agents/code-reviewer.md
    timeout: 120
    outputs:
      - issues_found
      - severity_level

  - name: security-audit
    agent: .claude/agents/security-auditor.md
    onFail: warn
    inputs:
      focus_areas: "SQL injection, XSS, authentication"

  - name: quality-check
    agent: .claude/agents/quality-checker.md
    commitMessage: "Improve code quality based on metrics"

  - name: code-reducer
    agent: .claude/agents/code-reducer.md
    enabled: true

  - name: memory-manager
    agent: .claude/agents/memory-updater.md
    commitMessage: "Update project memory with learnings"
