name: parallel-example
trigger: manual

settings:
  autoCommit: true
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: stop
  executionMode: parallel  # Enable parallel execution
  # permissionMode: acceptEdits  # default: auto-accept file edits (respects .claude/settings.json rules)

  # claudeAgent:                 # Optional: Claude Agent SDK settings
  #   model: sonnet              # haiku (fast/cheap) | sonnet (balanced) | opus (powerful)
  #   maxTurns: 15               # Max conversation turns
  #   maxThinkingTokens: 5000    # Extended thinking budget

agents:
  # These three stages run in parallel (no dependencies)
  - name: code-review
    agent: .claude/agents/code-reviewer.md
    timeout: 120
    outputs:
      - issues_found
      - severity
      - recommendations
    # claudeAgent:               # Optional: Per-stage override
    #   model: haiku             # Use fast, cheap model for simple reviews
    #   maxTurns: 10

  - name: security-scan
    agent: .claude/agents/security-auditor.md
    timeout: 120
    outputs:
      - vulnerabilities
      - risk_level
    retry:
      maxAttempts: 3
      backoff: exponential
      initialDelay: 1000
    # claudeAgent:               # Optional: Per-stage override
    #   model: opus              # Use powerful model for security analysis
    #   maxThinkingTokens: 10000

  - name: performance-check
    agent: .claude/agents/quality-checker.md
    timeout: 120
    outputs:
      - performance_score
      - bottlenecks

  # This stage depends on all three above (runs after they complete)
  - name: summary-report
    agent: .claude/agents/hello-world.md
    dependsOn:
      - code-review
      - security-scan
      - performance-check
    inputs:
      task: "Generate a summary report from previous stage outputs"
