# Large Pipeline Example
#
# This example demonstrates a large, multi-stage pipeline with parallel execution
# and complex dependencies. Uses file-based handover for inter-stage communication.

name: large-pipeline-example
trigger: manual

settings:
  autoCommit: true
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: continue
  preserveWorkingTree: false
  executionMode: parallel

# Git workflow with branch isolation
git:
  baseBranch: main
  branchStrategy: reusable
  pullRequest:
    autoCreate: true
    title: "🤖 Large Pipeline - {{pipelineName}}"
    reviewers: []
    labels:
      - automated
      - pipeline
    draft: false

# Notification configuration
notifications:
  enabled: true
  events:
    - pipeline.completed
    - pipeline.failed
  channels:
    local:
      enabled: true
      sound: true

agents:
  # Stage 1: Initial code review
  - name: code-review
    agent: .claude/agents/code-reviewer.md

  # Stage 2: Security audit (parallel with quality check)
  - name: security-audit
    agent: .claude/agents/security-auditor.md

  # Stage 3: Quality check (parallel with security audit)
  - name: quality-check
    agent: .claude/agents/quality-checker.md

  # Stage 4: Documentation update
  - name: doc-update
    agent: .claude/agents/doc-updater.md
    dependsOn:
      - code-review
      - security-audit
      - quality-check

  # Stage 5: Dependency audit
  - name: dependency-audit
    agent: .claude/agents/dependency-auditor.md

  # Stage 6: Performance analysis
  - name: performance-analysis
    agent: .claude/agents/quality-checker.md
    inputs:
      focus_areas: "performance, optimization"

  # Stage 7: Test coverage check
  - name: test-coverage
    agent: .claude/agents/quality-checker.md
    inputs:
      focus_areas: "test coverage, edge cases"

  # Stage 8: Code consolidation
  - name: code-consolidation
    agent: .claude/agents/code-reducer.md
    dependsOn:
      - code-review
      - quality-check

  # Stage 9: Memory management review
  - name: memory-review
    agent: .claude/agents/memory-updater.md

  # Stage 10: Final summary report
  - name: summary-report
    agent: .claude/agents/summary.md
    dependsOn:
      - code-review
      - security-audit
      - quality-check
      - doc-update
      - dependency-audit
      - performance-analysis
      - test-coverage
      - code-consolidation
      - memory-review

  # Stage 11: Cleanup
  - name: cleanup
    agent: .claude/agents/cleanup-reporter.md
    dependsOn:
      - summary-report
