# Loop Pipeline Example
# Demonstrates pipeline-level looping configuration
# Docs: https://github.com/FRE-Studios/agent-pipeline

name: loop-example
trigger: manual

agents:
  - name: story-writer
    agent: .agent-pipeline/agents/story_writer.md
    timeout: 300

looping:
  enabled: true
  maxIterations: 5

# Handover settings - inter-stage communication
handover:
  directory: pipeline-runs/loop-example

# Notification configuration (optional)
notifications:
  enabled: true


