# Loop Pipeline Example
# Demonstrates pipeline-level looping configuration
# Docs: https://github.com/FRE-Studios/agent-pipeline
#
# This pipeline auto-loops when run because looping.enabled: true
# No --loop CLI flag needed! The final stage agent receives instructions
# to create new pipeline files in the pending directory when needed.
#
# Usage:
#   agent-pipeline run loop-example           # Auto-loops
#   agent-pipeline run loop-example --no-loop # Force single run

name: loop-example
trigger: manual

settings:
  autoCommit: false
  commitPrefix: "[loop:{{stage}}]"
  failureStrategy: continue
  executionMode: sequential
  handover:
    directory: pipeline-runs/loop-example

# Pipeline-level looping configuration
# When enabled: true, pipeline automatically runs in loop mode
looping:
  enabled: true
  maxIterations: 10                 # Safety limit (default: 100)
  directories:                      # Optional - these are the defaults
    pending: next/pending           # Agents write new pipeline YAMLs here
    running: next/running           # Currently executing pipeline
    finished: next/finished         # Successfully completed pipelines
    failed: next/failed             # Failed pipeline files

notifications:
  enabled: true
  events:
    - pipeline.completed
    - pipeline.failed
  channels:
    local:
      enabled: true
      sound: true

agents:
  - name: story-writer
    agent: .agent-pipeline/agents/story_writer.md
    timeout: 300
