name: post-merge-example
trigger: post-merge

# Git workflow configuration for post-merge cleanup
git:
  baseBranch: main
  branchStrategy: reusable
  branchPrefix: pipeline
  pullRequest:
    autoCreate: true
    title: "🧹 Post-Merge Cleanup - {{pipelineName}}"
    labels:
      - automated
      - cleanup
      - post-merge

# Notification configuration
notifications:
  enabled: true
  events:
    - pipeline.completed
    - pipeline.failed
  channels:
    local:
      enabled: true
      sound: true
      openUrl: true

settings:
  autoCommit: true
  commitPrefix: "[cleanup:{{stage}}]"
  failureStrategy: continue  # Continue even if some cleanup fails
  preserveWorkingTree: false
  executionMode: parallel

# Agent stages
agents:
  # Run cleanup tasks in parallel after merge
  - name: doc-sync
    agent: .claude/agents/doc-updater.md
    timeout: 300

  - name: dependency-audit
    agent: .claude/agents/dependency-auditor.md
    timeout: 300

  - name: code-consolidation
    agent: .claude/agents/code-reducer.md
    timeout: 300

  # Generate summary report after all cleanup completes
  - name: summary-report
    agent: .claude/agents/cleanup-reporter.md
    dependsOn:
      - doc-sync
      - dependency-audit
      - code-consolidation
    timeout: 300
    commitMessage: "Add post-merge cleanup summary"
