name: post-commit-example
trigger: post-commit

# Settings for pipeline execution
settings:
  autoCommit: true                  # Enable when agents should commit fixes after each stage
  commitPrefix: "[pipeline:{{stage}}]"  # Standardized prefix for easy commit filtering
  failureStrategy: continue         # Continue even if a stage fails
  executionMode: sequential         # Enforce ordered execution for dependent stages

# Git workflow configuration (required for hook install)
git:
  baseBranch: main                  # PR base and merge target for the pipeline branch
  branchStrategy: unique-per-run    # Avoid branch contention for hook-triggered runs (use unique-and-delete to auto-cleanup)
  branchPrefix: review-pipeline     # Keeps pipeline branches easy to find/clean up
  pullRequest:
    autoCreate: false               # Keep off by default for local post-commit automation
    title: "🤖 Automated Code Review - {{pipelineName}}"  # PR title when autoCreate is enabled
    reviewers: []                   # Optional reviewers when autoCreate is enabled
    labels:
      - automated                   # Optional PR label when autoCreate is enabled
      - code-review

# Notification configuration (optional)
notifications:
  enabled: true                    # Enable local notifications for hook runs
  events:
    - pipeline.completed           # Notify on successful runs
    - pipeline.failed              # Notify on failures
  channels:
    local:
      enabled: true                # Desktop notifications (macOS/Linux)
      sound: true                  # Play a sound on completion

# Agent stages
agents:
  # Sequential execution: code-review → quality-check → doc-updater
  # Each stage builds on the previous stage's results
  - name: code-review
    agent: .agent-pipeline/agents/code-reviewer.md
    timeout: 300                    # Hard limit per agent run (seconds)

  - name: quality-check
    agent: .agent-pipeline/agents/quality-checker.md
    dependsOn:
      - code-review
    timeout: 300                    # Hard limit per agent run (seconds)
    onFail: warn                    # Non-blocking: log but keep running

  - name: doc-updater
    agent: .agent-pipeline/agents/doc-updater.md
    dependsOn:
      - quality-check
    timeout: 300                    # Hard limit per agent run (seconds)
