# Post-Commit Review Pipeline
# Automated code review triggered after each commit
# Default: 1 agent (doc-updater). Uncomment the full flow below for comprehensive review.
# Docs: https://github.com/FRE-Studios/agent-pipeline

name: post-commit-example
trigger: post-commit

# Settings for pipeline execution
settings:
  autoCommit: true                  # Enable when agents should commit fixes after each stage
  commitPrefix: "[pipeline:{{stage}}]"  # Standardized prefix for easy commit filtering
  failureStrategy: continue         # Continue even if a stage fails
  executionMode: sequential         # Enforce ordered execution for dependent stages

# Git workflow configuration (required for hook install)
git:
  baseBranch: main                  # PR base and merge target for the pipeline branch
  branchStrategy: unique-and-delete # Self-cleaning: auto-removes worktree on success, preserves on failure for debugging
  branchPrefix: review-pipeline     # Keeps pipeline branches easy to find/clean up
  mergeStrategy: pull-request       # Options: 'pull-request' (push + PR), 'local-merge' (merge locally), 'none' (keep on branch)
  pullRequest:
    title: "🤖 Automated Code Review - {{pipelineName}}"  # PR title
    reviewers: []                   # Optional GitHub usernames to request review from
    labels:
      - automated                   # Optional PR labels
      - code-review

# Notification configuration (optional)
notifications:
  enabled: true                    # Enable local notifications for hook runs
  events:
    - pipeline.completed           # Notify on successful runs
    - pipeline.failed              # Notify on failures
    - pr.created                   # Notify on new PR
  channels:
    local:
      enabled: true                # Desktop notifications (macOS/Linux)
      sound: true                  # Play a sound on completion

# Agent stages
agents:

  # # Example Single Agent  
  - name: doc-updater
    agent: .agent-pipeline/agents/doc-updater.md
    timeout: 300        

  # # Example Flow - Remove comments to run full pipeline 
  # # Warning - Pipelines may use many tokens, use with caution. 

  # # Sequential execution: code-review → quality-check → doc-updater
  # # Each stage builds on the previous stage's results
  # - name: code-review
  #   agent: .agent-pipeline/agents/code-reviewer.md
  #   timeout: 900                    # Hard limit per agent run (seconds)

  # - name: quality-check
  #   agent: .agent-pipeline/agents/quality-checker.md
  #   dependsOn:
  #     - code-review
  #   timeout: 900                    # Hard limit per agent run (seconds)
  #   onFail: warn                    # Non-blocking: log but keep running

  # - name: doc-updater
  #   agent: .agent-pipeline/agents/doc-updater.md
  #   dependsOn:
  #     - quality-check
  #   timeout: 300                    # Hard limit per agent run (seconds)
