name: post-commit-example
trigger: post-commit

# Settings for pipeline execution
settings:
  autoCommit: true
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: continue
  preserveWorkingTree: false
  executionMode: parallel

# Git workflow configuration (optional)
# git:
#   baseBranch: main
#   branchStrategy: reusable
#   pullRequest:
#     autoCreate: true
#     title: "🤖 Automated Code Review - {{pipelineName}}"
#     reviewers: []
#     labels:
#       - automated
#       - code-review

# Notification configuration (optional)
# notifications:
#   enabled: true
#   events:
#     - pipeline.completed
#     - pipeline.failed
#   channels:
#     local:
#       enabled: true
#       sound: true

# Agent stages
agents:
  # Sequential execution: code-review → quality-check → doc-updater
  # Each stage builds on the previous stage's results
  - name: code-review
    agent: .agent-pipeline/agents/code-reviewer.md
    timeout: 300

  - name: quality-check
    agent: .agent-pipeline/agents/quality-checker.md
    dependsOn:
      - code-review
    timeout: 300
    onFail: warn

  - name: doc-updater
    agent: .agent-pipeline/agents/doc-updater.md
    dependsOn:
      - quality-check
    timeout: 300
