name: pre-commit-example
trigger: pre-commit

# Pre-commit pipelines should be fast and fail-fast
settings:
  autoCommit: false  # Don't auto-commit in pre-commit hooks
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: stop  # Stop on first failure
  preserveWorkingTree: true  # Preserve working tree state
  executionMode: parallel

  # Context reduction for multi-stage pipelines
  contextReduction:
    enabled: true
    maxTokens: 50000              # Token limit for context
    strategy: summary-based       # summary-based or agent-based
    contextWindow: 3              # Number of recent stages to include in full
    requireSummary: true          # Require summary field from agents
    saveVerboseOutputs: true      # Save full outputs to .agent-pipeline/outputs/
    compressFileList: true        # Compress changed files list

# Agent stages
agents:
  # Run validation checks in parallel for speed
  - name: lint-check
    agent: .claude/agents/quality-checker.md
    timeout: 180
    onFail: stop

  - name: security-scan
    agent: .claude/agents/security-auditor.md
    timeout: 180
    onFail: stop

  # Generate summary only if all checks pass
  - name: validation-summary
    agent: .claude/agents/summary.md
    dependsOn:
      - lint-check
      - security-scan
    timeout: 120
