name: pre-push-example
trigger: pre-push

# Pre-push is a good time for comprehensive checks
settings:
  autoCommit: false  # Don't auto-commit in pre-push hooks
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: stop  # Stop on first failure
  preserveWorkingTree: true
  executionMode: parallel

# Agent stages
agents:
  # Run comprehensive checks in parallel
  - name: security-audit
    agent: .claude/agents/security-auditor.md
    timeout: 300
    onFail: stop

  - name: code-quality
    agent: .claude/agents/quality-checker.md
    timeout: 300
    onFail: stop

  - name: dependency-check
    agent: .claude/agents/dependency-auditor.md
    timeout: 300
    onFail: warn

  # Summarize all checks
  - name: push-approval
    agent: .claude/agents/summary.md
    dependsOn:
      - security-audit
      - code-quality
      - dependency-check
    timeout: 180
