name: pre-push-example
trigger: pre-push

# Pre-push is a good time for comprehensive checks
settings:
  autoCommit: false  # Don't auto-commit in pre-push hooks
  commitPrefix: "[pipeline:{{stage}}]"
  failureStrategy: stop  # Stop on first failure
  preserveWorkingTree: true
  executionMode: parallel

  # Context reduction for multi-stage pipelines
  contextReduction:
    enabled: true
    maxTokens: 50000              # Token limit for context
    strategy: summary-based       # summary-based or agent-based
    contextWindow: 3              # Number of recent stages to include in full
    requireSummary: true          # Require summary field from agents
    saveVerboseOutputs: true      # Save full outputs to .agent-pipeline/outputs/
    compressFileList: true        # Compress changed files list

# Agent stages
agents:
  # Run comprehensive checks in parallel
  - name: security-audit
    agent: .claude/agents/security-auditor.md
    timeout: 300
    onFail: stop
    outputs:
      - vulnerabilities
      - severity

  - name: code-quality
    agent: .claude/agents/quality-checker.md
    timeout: 300
    onFail: stop

  - name: dependency-check
    agent: .claude/agents/dependency-auditor.md
    timeout: 300
    onFail: warn

  # Only proceed with push if critical checks pass
  - name: push-approval
    agent: .claude/agents/summary.md
    dependsOn:
      - security-audit
      - code-quality
      - dependency-check
    condition: "{{ stages.security-audit.outputs.vulnerabilities == 0 }}"
    timeout: 180
