name: test-pipeline
trigger: manual

# Game-based pipeline showcasing inter-agent file communication
settings:
  autoCommit: false                    # No git commits for this demo
  commitPrefix: "[pipeline:{{stage}}]" # Not used but required
  failureStrategy: continue            # Continue even if agents fail
  preserveWorkingTree: true            # Don't touch working tree
  executionMode: parallel              # Enable DAG-based parallelism

agents:
  # STAGE 1: Storyteller creates the statements
  - name: storyteller
    agent: .agent-pipeline/agents/storyteller.md
    timeout: 300

  # STAGE 2: Five detectives analyze in parallel
  - name: logician
    agent: .agent-pipeline/agents/detective-logician.md
    dependsOn:
      - storyteller
    timeout: 300

  - name: empath
    agent: .agent-pipeline/agents/detective-empath.md
    dependsOn:
      - storyteller
    timeout: 300

  - name: statistician
    agent: .agent-pipeline/agents/detective-statistician.md
    dependsOn:
      - storyteller
    timeout: 300

  - name: linguist
    agent: .agent-pipeline/agents/detective-linguist.md
    dependsOn:
      - storyteller
    timeout: 300

  - name: skeptic
    agent: .agent-pipeline/agents/detective-skeptic.md
    dependsOn:
      - storyteller
    timeout: 300

  # STAGE 3: Synthesizer combines detective reasoning
  - name: synthesizer
    agent: .agent-pipeline/agents/synthesizer.md
    dependsOn:
      - logician
      - empath
      - statistician
      - linguist
      - skeptic
    timeout: 300

  # STAGE 4: Judge reveals truth and scores
  - name: judge
    agent: .agent-pipeline/agents/judge.md
    dependsOn:
      - synthesizer
    timeout: 300
